"""empty message

Revision ID: 77779bc30e69
Revises: d132282624da
Create Date: 2018-08-22 11:45:17.355570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77779bc30e69'
down_revision = 'd132282624da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
